### ISSUE TITLE
Usage? report errors

### ISSUE THREAD

**Issue by iamdye** [KRypt0nn/php-obfuscator#1]
Usage? report errors
![image](https://user-images.githubusercontent.com/32222007/90996188-97358400-e5f0-11ea-9a8b-246ccf8db5be.png)
![image](https://user-images.githubusercontent.com/32222007/90996241-b7fdd980-e5f0-11ea-9703-15ec7c38c986.png)

**Comment by krypt0nn** [comment]
You can use this library only with PHP 7.4. I think it can obfuscate code written in PHP 5.3 and upper, but I don't tested it :D

**Comment by iamdye** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Observer KRypt0n_"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 晚上6:25
收件人: "KRypt0nn/php-obfuscator"<php-obfuscator@noreply.github.com&gt;; 
抄送: "渡卑"<2522065507@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [KRypt0nn/php-obfuscator] Usage? report errors (#1)





 
Closed #1.
 
&mdash;
