### ISSUE TITLE
Ошибка что я делаю не так?

### ISSUE THREAD

**Issue by commeta** [KRypt0nn/php-obfuscator#2]
запускаю из терминала  php obfuscator.php код из примера
```php
require 'php-obfuscator/obfuscator.php';
use Obfuscator\Obfuscator;
echo Obfuscator::process (file_get_contents (__FILE__));
```

PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /home/bitrix/ext_www/php-obfuscator/bin/Obfuscator.php on line 19

**Comment by krypt0nn** [comment]
Почти на 100 % уверен что проблема в старой версии PHP. Обновитесь до 7.4+, либо до 8+, если позволяет система.
Не знаю почему не указал это на страничке проекта. Вроде просто не успел доделать 😅

**Comment by commeta** [comment]
Да на v7.2.34 не работает.
запустился на 7.4.3 (cli)
Но теперь другая ошибка
`php obfuscator.php 
PHP Fatal error:  Uncaught Error: Class 'Obfuscator\Modules\VarOptimizer' not found in /var/www/www-root/php-obfuscator/bin/Obfuscator.php:77
Stack trace:
#0 /var/www/www-root/obfuscator.php(8): Obfuscator\Obfuscator::process()
#1 {main}
  thrown in /var/www/www-root/php-obfuscator/bin/Obfuscator.php on line 77
`

**Comment by krypt0nn** [comment]
Ошибка вызвана тем, что банально не подключен файл `bin/modules/VarOptimizer.php`. На этот раз почти на 100 % уверен что вы неправильно подключаете библиотеку. Делать это надо через файл `obfuscator.php`, лежащий в корне репозитория. Если посмотрите, в нём прописано подключение всех модулей обфускатора

```php
<?php

require 'obfuscator.php';

namespace Obfuscator;

// your code goes here
```

**Comment by commeta** [comment]
Разобрался, спасибо!
